import type { WeddingThemePreset } from '@/types/wedding'
import { PUBLIC_SOURCE_THEME_PRESETS } from './sapatamu-source-themes'

export const BRAND = {
  name: 'Rekavia',
  tagline: 'Rekayasa Visual Anda',
  description: 'Platform untuk penjualan, pengelolaan, dan publikasi undangan digital dengan editor konten, slug kustom, RSVP, dan analitik.',
  domain: 'rekavia.id',
} as const

export const PRODUCTS = [
  {
    id: 'sapatamu',
    name: 'SapaTamu',
    tagline: 'Undangan Digital Premium',
    headline: 'Undangan pernikahan digital yang menyentuh hati',
    description: 'Buat undangan pernikahan digital yang elegan dengan berbagai tema premium, fitur RSVP, dan broadcast otomatis.',
    longDescription: 'Setiap kisah cinta layak diceritakan dengan indah. SapaTamu menghadirkan undangan digital yang bukan sekadar informasi — tapi pengalaman. Dari cover yang personal hingga RSVP otomatis, semua dirancang untuk momen terpenting dalam hidupmu.',
    icon: 'Heart',
    color: '#C45D3E',
    image: '/images/hero-sapatamu.png',
    href: '/produk/sapatamu',
    highlights: ['10 Tema Premium', 'Live Preview Editor', 'RSVP & Buku Tamu', 'Broadcast WhatsApp', 'Digital Angpao', 'Background Music'],
  },
  {
    id: 'etalasepro',
    name: 'EtalasePro',
    tagline: 'Toko Online UMKM',
    headline: 'Etalase digital untuk usahamu yang berkembang',
    description: 'Katalog produk digital untuk UMKM dengan manajemen inventaris, galeri produk, dan halaman toko profesional.',
    longDescription: 'Tidak perlu marketplace — punya toko sendiri yang bikin pelanggan percaya. EtalasePro memberikan halaman produk yang rapi, galeri yang memukau, dan informasi kontak yang jelas untuk UMKM-mu.',
    icon: 'ShoppingBag',
    color: '#3A7D44',
    image: '/images/hero-etalasepro.png',
    href: '/produk/etalasepro',
    highlights: ['Katalog Produk', 'Upload Foto Produk', 'Manajemen Ketersediaan', 'Profil Toko', 'Kontak WhatsApp', 'SEO Optimized'],
  },
  {
    id: 'citrakorpora',
    name: 'CitraKorpora',
    tagline: 'Company Profile Premium',
    headline: 'Tampil profesional di era digital',
    description: 'Website company profile profesional yang meninggalkan kesan mendalam bagi klien dan partner bisnis Anda.',
    longDescription: 'Kesan pertama menentukan segalanya. CitraKorpora membantu perusahaanmu tampil kredibel dengan website company profile yang bersih, informatif, dan mencerminkan identitas brand-mu.',
    icon: 'Building2',
    color: '#1B2A4A',
    image: '/images/hero-citrakorpora.png',
    href: '/produk/citrakorpora',
    highlights: ['Profil Perusahaan', 'Halaman Tim', 'Portofolio & Klien', 'Kontak & Map', 'Multi-page', 'Mobile Responsive'],
  },
  {
    id: 'edugerbang',
    name: 'EduGerbang',
    tagline: 'Website Sekolah Modern',
    headline: 'Gerbang digital untuk institusi pendidikan',
    description: 'Platform digital untuk institusi pendidikan: profil sekolah, pengumuman, galeri kegiatan, dan informasi akademik.',
    longDescription: 'Orang tua dan calon siswa perlu informasi yang mudah diakses. EduGerbang membuat sekolahmu tampil modern dengan profil lengkap, pengumuman terkini, galeri kegiatan, dan informasi akademik dalam satu platform.',
    icon: 'GraduationCap',
    color: '#D97706',
    image: '/images/hero-edugerbang.png',
    href: '/produk/edugerbang',
    highlights: ['Profil Sekolah', 'Pengumuman', 'Galeri Kegiatan', 'Info Akademik', 'Visi & Misi', 'Kontak & Peta'],
  },
] as const

export const PRODUCT_PRICING: Record<string, {
  basic: { name: string; price: number; period: string; features: { text: string; included: boolean }[] };
  pro: { name: string; price: number; period: string; badge?: string; features: { text: string; included: boolean }[] };
}> = {
  sapatamu: {
    basic: {
      name: 'Basic',
      price: 150000,
      period: '/tahun',
      features: [
        { text: 'Pilihan 10 tema premium', included: true },
        { text: 'Formulir RSVP terintegrasi', included: true },
        { text: 'Galeri foto (maks. 10)', included: true },
        { text: 'Countdown timer acara', included: true },
        { text: 'Subdomain rekavia.id', included: true },
        { text: 'Digital Angpao', included: false },
        { text: 'Broadcast WhatsApp Generator', included: false },
        { text: 'Galeri foto unlimited', included: false },
        { text: 'Custom domain', included: false },
        { text: 'Prioritas support', included: false },
      ],
    },
    pro: {
      name: 'Pro',
      price: 250000,
      period: '/tahun',
      badge: 'Populer',
      features: [
        { text: 'Pilihan 10 tema premium', included: true },
        { text: 'Formulir RSVP terintegrasi', included: true },
        { text: 'Galeri foto unlimited', included: true },
        { text: 'Countdown timer acara', included: true },
        { text: 'Subdomain rekavia.id', included: true },
        { text: 'Digital Angpao', included: true },
        { text: 'Broadcast WhatsApp Generator', included: true },
        { text: 'Background music kustom', included: true },
        { text: 'Custom domain', included: true },
        { text: 'Prioritas support', included: true },
      ],
    },
  },
  etalasepro: {
    basic: {
      name: 'Starter',
      price: 200000,
      period: '/tahun',
      features: [
        { text: 'Halaman toko online', included: true },
        { text: 'Katalog hingga 50 produk', included: true },
        { text: 'Upload foto produk', included: true },
        { text: 'Info kontak & WhatsApp', included: true },
        { text: 'Subdomain rekavia.id', included: true },
        { text: 'Produk unlimited', included: false },
        { text: 'Kategori produk kustom', included: false },
        { text: 'Custom domain', included: false },
        { text: 'Analitik pengunjung', included: false },
        { text: 'Prioritas support', included: false },
      ],
    },
    pro: {
      name: 'Business',
      price: 350000,
      period: '/tahun',
      badge: 'Best Value',
      features: [
        { text: 'Halaman toko online', included: true },
        { text: 'Produk unlimited', included: true },
        { text: 'Upload foto multi-angle', included: true },
        { text: 'Info kontak & WhatsApp', included: true },
        { text: 'Subdomain rekavia.id', included: true },
        { text: 'Kategori produk kustom', included: true },
        { text: 'Custom domain', included: true },
        { text: 'Analitik pengunjung', included: true },
        { text: 'Badge produk (Sale, New)', included: true },
        { text: 'Prioritas support', included: true },
      ],
    },
  },
  citrakorpora: {
    basic: {
      name: 'Professional',
      price: 300000,
      period: '/tahun',
      features: [
        { text: 'Landing page profesional', included: true },
        { text: 'Halaman About & Contact', included: true },
        { text: 'Galeri portofolio (maks. 20)', included: true },
        { text: 'Info kontak & map embed', included: true },
        { text: 'Subdomain rekavia.id', included: true },
        { text: 'Halaman tim & profil', included: false },
        { text: 'Multi-page (Services, Blog)', included: false },
        { text: 'Custom domain', included: false },
        { text: 'Analitik pengunjung', included: false },
        { text: 'Prioritas support', included: false },
      ],
    },
    pro: {
      name: 'Enterprise',
      price: 500000,
      period: '/tahun',
      badge: 'Premium',
      features: [
        { text: 'Landing page profesional', included: true },
        { text: 'Halaman About & Contact', included: true },
        { text: 'Galeri portofolio unlimited', included: true },
        { text: 'Info kontak & map embed', included: true },
        { text: 'Subdomain rekavia.id', included: true },
        { text: 'Halaman tim & profil', included: true },
        { text: 'Multi-page (Services, Blog)', included: true },
        { text: 'Custom domain', included: true },
        { text: 'Analitik pengunjung', included: true },
        { text: 'Prioritas support', included: true },
      ],
    },
  },
  edugerbang: {
    basic: {
      name: 'Sekolah Basic',
      price: 250000,
      period: '/tahun',
      features: [
        { text: 'Profil sekolah lengkap', included: true },
        { text: 'Halaman visi & misi', included: true },
        { text: 'Pengumuman (maks. 20)', included: true },
        { text: 'Galeri kegiatan', included: true },
        { text: 'Subdomain rekavia.id', included: true },
        { text: 'Pengumuman unlimited', included: false },
        { text: 'Info akademik & kurikulum', included: false },
        { text: 'Custom domain', included: false },
        { text: 'Kalender akademik', included: false },
        { text: 'Prioritas support', included: false },
      ],
    },
    pro: {
      name: 'Sekolah Pro',
      price: 400000,
      period: '/tahun',
      badge: 'Lengkap',
      features: [
        { text: 'Profil sekolah lengkap', included: true },
        { text: 'Halaman visi & misi', included: true },
        { text: 'Pengumuman unlimited', included: true },
        { text: 'Galeri kegiatan unlimited', included: true },
        { text: 'Subdomain rekavia.id', included: true },
        { text: 'Info akademik & kurikulum', included: true },
        { text: 'Kalender akademik', included: true },
        { text: 'Custom domain', included: true },
        { text: 'Halaman guru & staff', included: true },
        { text: 'Prioritas support', included: true },
      ],
    },
  },
}

export const PRICING = PRODUCT_PRICING.sapatamu

export const WEDDING_THEMES: WeddingThemePreset[] = [
  {
    id: 'floral',
    name: 'Floral Garden',
    group: 'Romantis',
    description: 'Nuansa taman bunga yang romantis dengan sentuhan watercolor',
    previewImage: '/themes/floral.jpg',
    primaryColor: '#8B5E3C',
    secondaryColor: '#F5E6D8',
    accentColor: '#D4956A',
    fontHeading: 'Playfair Display',
    fontBody: 'Lora',
    bgPattern: 'floral',
  },
  {
    id: 'minimalist',
    name: 'Clean Minimalist',
    group: 'Minimal',
    description: 'Desain bersih dan modern dengan tipografi yang kuat',
    previewImage: '/themes/minimalist.jpg',
    primaryColor: '#1A1A1A',
    secondaryColor: '#FAFAFA',
    accentColor: '#888888',
    fontHeading: 'Inter',
    fontBody: 'Inter',
  },
  {
    id: 'tradisional',
    name: 'Nusantara Heritage',
    group: 'Budaya',
    description: 'Keindahan motif batik dan ornamen Jawa yang anggun',
    previewImage: '/themes/tradisional.jpg',
    primaryColor: '#5C1A0B',
    secondaryColor: '#FFF8F0',
    accentColor: '#C8935F',
    fontHeading: 'Cormorant Garamond',
    fontBody: 'Source Sans 3',
    bgPattern: 'batik',
  },
  {
    id: 'premium1',
    name: 'Munggah Sriwijaya - Auburn Red',
    group: 'Budaya',
    description: 'Tema adat Palembang bernuansa auburn red dengan ornamen Sriwijaya',
    previewImage: '/sapatamu-themes/premium1/original/pictures/picture_17393765661722ej1do.jpeg',
    primaryColor: '#4a1a1f',
    secondaryColor: '#341215',
    accentColor: '#a97f71',
    fontHeading: 'Gautreaux',
    fontBody: 'Fahkwang',
    bgPattern: 'batik',
  },
  {
    id: 'sarune-batak-sangria',
    name: 'Sarune Batak - Sangria',
    group: 'Budaya',
    description: 'Tema adat Batak bernuansa sangria dengan ornamen Sarune',
    previewImage: '/sapatamu-themes/sarune-batak-sangria/original/pictures/picture_1739377539664wswbzef.jpeg',
    primaryColor: '#7b0f24',
    secondaryColor: '#230c10',
    accentColor: '#b55963',
    fontHeading: 'Annabelle-JF',
    fontBody: 'Fahkwang',
    bgPattern: 'batik',
  },
  ...PUBLIC_SOURCE_THEME_PRESETS,
  {
    id: 'modern',
    name: 'Urban Chic',
    group: 'Kontemporer',
    description: 'Gaya metropolitan dengan aksen geometris yang stylish',
    previewImage: '/themes/modern.jpg',
    primaryColor: '#0D1B2A',
    secondaryColor: '#F0F4F8',
    accentColor: '#E07A5F',
    fontHeading: 'Space Grotesk',
    fontBody: 'DM Sans',
  },
  {
    id: 'bnw',
    name: 'Monochrome Elegance',
    group: 'Editorial',
    description: 'Kemewahan hitam-putih yang tak lekang oleh waktu',
    previewImage: '/themes/bnw.jpg',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
    accentColor: '#666666',
    fontHeading: 'DM Serif Display',
    fontBody: 'Outfit',
  },
  {
    id: 'anime',
    name: 'Kawaii Story',
    group: 'Eksperimental',
    description: 'Ilustrasi bergaya anime yang playful dan penuh warna',
    previewImage: '/themes/anime.jpg',
    primaryColor: '#FF6B8A',
    secondaryColor: '#FFF0F3',
    accentColor: '#FFB4C7',
    fontHeading: 'Nunito',
    fontBody: 'Nunito Sans',
  },
  {
    id: 'retro',
    name: 'Vintage Romance',
    group: 'Editorial',
    description: 'Nuansa retro 70-an dengan palet warna hangat dan muted',
    previewImage: '/themes/retro.jpg',
    primaryColor: '#6B4226',
    secondaryColor: '#F9F3E8',
    accentColor: '#C98B5E',
    fontHeading: 'Fraunces',
    fontBody: 'Commissioner',
  },
  {
    id: 'gallery',
    name: 'Photo Gallery',
    group: 'Foto',
    description: 'Mengutamakan galeri foto full-width yang memukau',
    previewImage: '/themes/gallery.jpg',
    primaryColor: '#1A1A2E',
    secondaryColor: '#F5F5F5',
    accentColor: '#E94560',
    fontHeading: 'Syne',
    fontBody: 'Inter',
  },
]

export const NAV_LINKS = [
  { label: 'Produk', href: '/#produk' },
  { label: 'Cara Kerja', href: '/#cara-kerja' },
  { label: 'Tentang', href: '/#tentang' },
] as const

export const CMS_SIDEBAR_LINKS = {
  sapatamu: [
    { label: 'Editor', href: '/cms/sapatamu', icon: 'PenTool' },
    { label: 'Buku Tamu', href: '/cms/sapatamu/rsvp', icon: 'Users' },
    { label: 'Digital Angpao', href: '/cms/sapatamu/angpao', icon: 'Wallet' },
    { label: 'Broadcast', href: '/cms/sapatamu/broadcast', icon: 'Send' },
  ],
  etalasepro: [
    { label: 'Dashboard', href: '/cms/etalasepro', icon: 'LayoutDashboard' },
    { label: 'Produk', href: '/cms/etalasepro/produk', icon: 'Package' },
    { label: 'Profil Toko', href: '/cms/etalasepro/profil-toko', icon: 'ShoppingBag' },
    { label: 'Pengaturan', href: '/cms/etalasepro/pengaturan', icon: 'Settings' },
  ],
  citrakorpora: [
    { label: 'Dashboard', href: '/cms/citrakorpora', icon: 'LayoutDashboard' },
    { label: 'Profil Perusahaan', href: '/cms/citrakorpora/profil', icon: 'Building2' },
    { label: 'Tim', href: '/cms/citrakorpora/tim', icon: 'Users' },
    { label: 'Portofolio', href: '/cms/citrakorpora/portofolio', icon: 'Briefcase' },
  ],
  edugerbang: [
    { label: 'Dashboard', href: '/cms/edugerbang', icon: 'LayoutDashboard' },
    { label: 'Profil Sekolah', href: '/cms/edugerbang/profil', icon: 'Building2' },
    { label: 'Pengumuman', href: '/cms/edugerbang/pengumuman', icon: 'Megaphone' },
    { label: 'Galeri', href: '/cms/edugerbang/galeri', icon: 'Image' },
    { label: 'Akademik', href: '/cms/edugerbang/akademik', icon: 'BookOpen' },
  ],
  general: [
    { label: 'Dashboard', href: '/cms', icon: 'LayoutDashboard' },
    { label: 'Profil', href: '/cms/profil', icon: 'User' },
    { label: 'Langganan', href: '/cms/langganan', icon: 'CreditCard' },
  ],
  admin: [
    { label: 'Dashboard', href: '/admin', icon: 'LayoutDashboard' },
    { label: 'Users', href: '/admin/users', icon: 'Users' },
    { label: 'Finance', href: '/admin/finance', icon: 'CreditCard' },
    { label: 'Vouchers', href: '/admin/vouchers', icon: 'Wallet' },
    { label: 'Products', href: '/admin/products', icon: 'Package' },
    { label: 'Audit Log', href: '/admin/audit-logs', icon: 'History' },
    { label: 'Settings', href: '/admin/settings', icon: 'Settings' },
  ],
} as const

export const formatRupiah = (amount: number): string => {
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount)
}
